services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 application:application
    pythonVersion: 3.8  # Specify the Python version here
